production:
  environment: production
  production_environment: true

staging:
  auto_deploy_on: refs/tags/*
  environment: staging
  production_environment: false
  required_contexts: ["build"]

review:
  environment: pr${{ pr }}
  transient_environment: true
  production_environment: false
